// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbp4ms5_IcNBDctrhDgqHi8lQ5db-Y0yU',
    appId: '1:618149502443:web:4012da2b4d26dbc40f0dae',
    messagingSenderId: '618149502443',
    projectId: 'adibfarhan-prodib',
    authDomain: 'adibfarhan-prodib.firebaseapp.com',
    storageBucket: 'adibfarhan-prodib.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaUAvUYvM-u81wE1cq6kmYTe5UaAsTJkI',
    appId: '1:618149502443:android:d98912eb7f3d97030f0dae',
    messagingSenderId: '618149502443',
    projectId: 'adibfarhan-prodib',
    storageBucket: 'adibfarhan-prodib.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADAUSD6KwezUWntV3gtYhjCQhZ1KCQxuY',
    appId: '1:618149502443:ios:9ca6da9f153ce45a0f0dae',
    messagingSenderId: '618149502443',
    projectId: 'adibfarhan-prodib',
    storageBucket: 'adibfarhan-prodib.firebasestorage.app',
    iosBundleId: 'com.example.p42200016102Muhammadadibfarhan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADAUSD6KwezUWntV3gtYhjCQhZ1KCQxuY',
    appId: '1:618149502443:ios:9ca6da9f153ce45a0f0dae',
    messagingSenderId: '618149502443',
    projectId: 'adibfarhan-prodib',
    storageBucket: 'adibfarhan-prodib.firebasestorage.app',
    iosBundleId: 'com.example.p42200016102Muhammadadibfarhan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbp4ms5_IcNBDctrhDgqHi8lQ5db-Y0yU',
    appId: '1:618149502443:web:2e44cdf92487ac8c0f0dae',
    messagingSenderId: '618149502443',
    projectId: 'adibfarhan-prodib',
    authDomain: 'adibfarhan-prodib.firebaseapp.com',
    storageBucket: 'adibfarhan-prodib.firebasestorage.app',
  );

}